imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.filesystem

web_profiler:
    toolbar: false
    intercept_redirects: false

#swiftmailer:
#    disable_delivery: true

doctrine:
  dbal:
      driver:   "pdo_sqlite"
      path:     ":memory:"
      port:     "%database_port%"
      memory:   true

  orm:
      auto_generate_proxy_classes: "%kernel.debug%"
      auto_mapping: true

